# Generated by Django 5.2 on 2025-04-17 09:44

import blogs.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, unique=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Enter valid SVG code (e.g., <svg>...</svg>).', null=True, validators=[blogs.models.validate_svg_content])),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tthumbnail', models.ImageField(blank=True, null=True, upload_to=blogs.models.get_image_filename, validators=[blogs.models.validate_image_extension, blogs.models.validate_image_size])),
                ('thumbnail_url', models.URLField(blank=True, validators=[django.core.validators.RegexValidator(message='URL must point to a valid image (JPG, JPEG, PNG, or GIF).', regex='\\.(jpg|jpeg|png|gif)$')])),
                ('snippet', models.CharField(max_length=255)),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(50, 'Post body must be at least 50 characters long.')])),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blogs.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['slug'], name='blogs_post_slug_582fe9_idx'), models.Index(fields=['date'], name='blogs_post_date_556eec_idx'), models.Index(fields=['category'], name='blogs_post_categor_b4f82a_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_post_slug')],
            },
        ),
    ]
