# Generated by Django 5.2 on 2025-04-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tthumbnail',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='testing', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
